### ISSUE TITLE
nginx script updates

### ISSUE THREAD

**Issue by time4tea** [redbadger/stack#12]
tweak the nginx script - seemed to be pointing to the wrong port otherwise? also location fiddle for websockets. Sorry for the old fashioned patch.
James

```
diff --git a/nginx/default.conf b/nginx/default.conf
index f05c5a0..e124d65 100644
--- a/nginx/default.conf
+++ b/nginx/default.conf
@@ -9,6 +9,12 @@ server {
   location / {
     proxy_pass http://web;
   }
+  location /stream {
+    proxy_pass http://web;
+    proxy_http_version 1.1;
+    proxy_set_header Upgrade $http_upgrade;
+    proxy_set_header Connection "upgrade";
+  }
   location /api {
     rewrite ^/api/(.*)$ /$1 break;
     proxy_pass http://api;
diff --git a/nginx/start.sh b/nginx/start.sh
index 17faf66..6ef58db 100644
--- a/nginx/start.sh
+++ b/nginx/start.sh
@@ -7,7 +7,7 @@ nodes=$(docker-machine ip $(docker-machine ls -q))
 str=''
 for node in $nodes
 do
-  str="$str  server $node;"
+  str="$str  server $node:8080;"
 done
 echo $str
 
```

**Comment by charypar** [comment]
@time4tea I brought some changes back from the internal setup to make the whole stack a little more complex, but also more 12-factor. The service linking should now be a bit cleaner and, crucially, the outer nginx should proxy/load-balance correctly across both the app and the services stack. 

Can you please check #13 and see whether it does what you expected?

**Comment by StuartHarris** [comment]
p.s. the app is on http://localhost and the visualiser on http://localhost/_cluster/swarm/
